version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.local
    volumes:
      - .:/app
    ports:
      - "8011:8011"
    tty: true
    env_file:
      - "./backend/.env"
